# Generated by Django 4.2.3 on 2023-09-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
